name = "thunder-worker"
main = "src/worker.ts"
compatibility_date = "2025-09-10"

[[kv_namespaces]]
binding = "KV"
id = "thunder_kv" # 실제 바인딩 ID로 교체

[vars]
ORIGIN_ALLOW = "https://cjsend-gif.github.io"

# 로컬 미리보기용
[observability]
enabled = true

