name: Deploy Thunder
permissions:
  contents: write  # 예: 파일 수정 권한
  id-token: write  # id-token을 생성하고 쓸 수 있는 권한 추가
on:
  push:
    branches: [ main ]
jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload static to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
  worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: deploy worker/src/worker.ts
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          ORIGIN_ALLOW: https://cjsend-gif.github.io

